--- pyproject.toml.orig	2024-09-09 21:16:54 UTC
+++ pyproject.toml
@@ -1,3 +1,3 @@
 [build-system]
-requires=['setuptools>=68.0', 'numpy>=1.25,<2.0.0', 'scipy>=1.12', 'cykhash>=2.0,<3.0', 'Cython>=3.0,<3.1', 'scikit-learn>=1.3', 'hmmlearn>=0.3.2']
+requires=['setuptools>=68.0', 'numpy>=1.25,<2.0.0', 'scipy>=1.11.1', 'cykhash>=2.0,<3.0', 'Cython>=0', 'scikit-learn>=1.3', 'hmmlearn>=0.3.2']
 
